# Generated by Django 3.1.3 on 2020-12-29 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('book_name', models.CharField(max_length=50)),
                ('borrow_num', models.IntegerField()),
                ('borrow_time', models.DateField()),
                ('fines', models.CharField(max_length=10)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book.bookinfo', verbose_name='book id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.userinfo', verbose_name='user id')),
            ],
        ),
    ]
