# Generated by Django 3.1.3 on 2020-12-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('permission', models.CharField(choices=[(0, 'Reader'), (1, 'Administrator')], default=0, max_length=20)),
                ('gender', models.CharField(choices=[(0, 'male'), (1, 'female')], default=0, max_length=2)),
            ],
        ),
    ]
