# Generated by Django 3.1.3 on 2020-12-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(default='male', max_length=20),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='permission',
            field=models.CharField(default='reader', max_length=20),
        ),
    ]
